brought in changes from trunk
git-svn-id: https://svn.kuali.org/repos/student/tools/ks-jenkins/branches/impex-credentials-fix@72994 0ac02d80-fb3f-11dc-a574-c57244a850eb

diff --git a/all-in-one-aft b/all-in-one-aft
--- a/all-in-one-aft
+++ b/all-in-one-aft
@@ -10,9 +10,10 @@ MVN="mvn"
 AFT_URL="https://svn.kuali.org/repos/student/test/functional-automation/sambal/trunk"
 
 # tomcat variables
-TOMCAT_VERSION=7.0.54
+TOMCAT_VERSION=7.0.55
 export CATALINA_HOME=${WORKSPACE}/tomcat
 export CATALINA_OPTS="-Xms512m -Xmx4g -XX:MaxPermSize=512m -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintHeapAtGC -XX:+PrintTenuringDistribution -Xloggc:${WORKSPACE}/tomcat/logs/heap.log -XX:HeapDumpPath=${WORKSPACE}/tomcat/logs -XX:+HeapDumpOnOutOfMemoryError"
+export CATALINA_PID=$(mktemp --suffix .ksaft.catalina)
 
 function usage() {
   cat <<EOT
@@ -103,7 +104,6 @@ function initialize_schema() {
     -e "s#\${jdbc.password}#${SANITIZED_SCHEMA^^}#g" \
     -e 's#${jdbc.pool.size.max}#20#g' \
     -e 's#${rice.krad.dev.mode}#false#g' \
-    -e 's#${rice.krad.script.cleanup}#false#g' \
     -e 's#${keystore.file.default}#/rice.keystore#g' \
         ~/kuali/main/dev/ks-with-rice-bundled-config.xml
 
@@ -127,9 +127,9 @@ function download_tomcat() {
     http://archive.apache.org/dist/tomcat/tomcat-7/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz
 
   # stop building if md5sum does not match
-  echo "e43771bc8c6a10956495d13300567244  /tmp/apache-tomcat-$TOMCAT_VERSION.tar.gz" | \
+  echo "3c46fc0f608c1280dcd65100a983f285  /tmp/apache-tomcat-$TOMCAT_VERSION.tar.gz" | \
     md5sum -c
-  echo "${FUNCNAME[0]}: download tomcat $TOMCAT_VERSION."
+  echo "${FUNCNAME[0]}: downloaded tomcat $TOMCAT_VERSION."
 }
 
 function extract_tomcat() {
@@ -227,10 +227,11 @@ function install_war_artifact() {
 function start_tomcat() {
   dbgprint
 
+  rm -f $CATALINA_PID
   # start up tomcat
   dbgprint ${CATALINA_HOME}/bin/startup.sh
   echo "Staring Tomcat..."
-  ${CATALINA_HOME}/bin/startup.sh
+  ${CATALINA_HOME}/bin/startup.sh 2>&1
 
   # timeout will be exceeded in LIMIT*SLEEP seconds
   LIMIT=30
@@ -258,7 +259,7 @@ function start_tomcat() {
   if [ $a -ge "$LIMIT" ]
   then
     echo "Timeout of $(($LIMIT*$SLEEP)) seconds exceeded"
-    shutdown_tomcat
+    cleanup_tomcat
     exit 1
   fi
 
@@ -284,10 +285,13 @@ function run_afts() {
   echo "${FUNCNAME[0]}: AFTs finished."
 }
 
-function shutdown_tomcat() {
+function cleanup_tomcat() {
   dbgprint
 
-  pkill -9 -f catalina
+  # wait 30 seconds while sutting down tomcat, then use force!!
+  ${CATALINA_HOME}/bin/shutdown.sh 30 -force 2>&1
+  echo "waiting for Tomcat to exit (PID: $(cat $CATALINA_PID))... "
+  wait $(cat $CATALINA_PID)
   echo "${FUNCNAME[0]}: tomcat shutdown finished."
 }
 
@@ -400,13 +404,18 @@ install_war_artifact
 # initialize schema (using impex)
 initialize_schema
 
+# register the cleanup function as callback to execute when a signal
+# is sent to this process
+trap cleanup_tomcat EXIT SIGINT SIGTERM
+
 # start tomcat
 start_tomcat
 
 # run AFTs
 run_afts
 
-# shutdown tomcat
-shutdown_tomcat
+# process was successful, so reset trap and cleanup normally
+trap - EXIT SIGINT SIGTERM
+cleanup_tomcat
 
 # vim: tabstop=2 shiftwidth=2
